title: Your Name
description: Robotics & Computer Vision Student
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Social links for the sidebar
google_analytics: 
github_username: your-github-handle
linkedin_username: your-linkedin-handle
